language: android
jdk: oraclejdk8

android:
  components:
    # Update Android SDK Tools
    - tools
    - build-tools-27
    - android-27
    # Support library
    - extra-android-support
    - extra-android-m2repository

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle

#script: ./gradlew test
